### PR TITLE
moved hypershift metadata collection in to respective class

### PR DESCRIPTION
**Pull request by mukrishn**
## Type of change

- [x] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Fixes #28 comment to move this metadata collection out of `utils.py`.
This has to go in before that PR.

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

### CODE REVIEW

**Review by krishvoor — APPROVED** [review]
/lgtm

**Review by krishvoor — APPROVED** [review]
lgtm

**Review by krishvoor — APPROVED** [review]
lgtm

**Review by morenod — APPROVED** [review]
lgtm

**Pull request merged**
